const mongoose=require('mongoose');
const PostSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
    },
    char:{
        type:String,
        required:false,
    },
    photo:{
        type:String,
        required:false,
    },
    author:{
        type:String,
        required:true,
    },
    position:{
        type:String,
        require:true,
    },
    category:{
        type:String,
        require:true,
    }
})
{timestamp:true}
module.exports=mongoose.model('Post',PostSchema);
